// Event categories configuration
export const EVENT_CATEGORIES = [
    {
        code: 'MNR',
        name: 'Mini Sumo RC',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'MGR',
        name: 'Mega Sumo RC',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'MNA',
        name: 'Mini Sumo Auto',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'MGA',
        name: 'Mega Sumo Auto',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'RRC',
        name: 'Robot Rugby',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 4,
    },
    {
        code: 'DRC',
        name: 'Drone RC',
        maxTeamsPerOrg: 5,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'DRA',
        name: 'Drone Auto',
        maxTeamsPerOrg: 5,
        minContestantsPerTeam: 1,
    },
    {
        code: 'LFG',
        name: 'Line Follower (Lego)',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'LFH',
        name: 'Line Follower (High Speed)',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'LFL',
        name: 'Line Follower (Low Speed)',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'LSR',
        name: 'Lego Sumo',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 2,
    },
    {
        code: 'LUR',
        name: 'Lego Unknown',
        maxTeamsPerOrg: 10,
        minContestantsPerTeam: 1,
        maxContestantsPerTeam: 3,
    },
];
